### ISSUE TITLE
custom HOC not working when multiple hocs declaration and no state and actions

### ISSUE THREAD

**Issue by pbebespoon** [pbenard73/reactizy#1]
Custom hocs are not binding to my component

```
//myHoc.js
export default hocBuilder({
     alert: withAlert()
},
{
     askDeletion: function() {}
}
)
```

myComponent
`export default myHoc(["askDeletion", "alert"])(MyComponent)`

The `props.askDeletion` and `props.alert` are not present,

**Comment by pbenard73** [comment]
fix in 2.1.1
